#!/usr/bin/env bash
# Download all recommended photography assets
# Unsplash: https://unsplash.com/photos/{ID}/download?force=true
# Pexels: https://images.pexels.com/photos/{ID}/pexels-photo-{ID}.jpeg?auto=compress&cs=tinysrgb&w=1280

set -euo pipefail
BASE="/Users/wc-design/Downloads/Anyinterview.to/photography"
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"

dl_unsplash() {
  local id="$1" folder="$2" name="$3"
  local out="$BASE/$folder/$name.jpg"
  [[ -f "$out" ]] && echo "  skip: $name" && return
  echo "  → unsplash/$id → $folder/$name.jpg"
  curl -sL -A "$UA" \
    "https://unsplash.com/photos/$id/download?force=true" \
    -o "$out" || echo "  FAIL: $id"
}

dl_pexels() {
  local id="$1" folder="$2" name="$3"
  local out="$BASE/$folder/$name.jpg"
  [[ -f "$out" ]] && echo "  skip: $name" && return
  echo "  → pexels/$id → $folder/$name.jpg"
  curl -sL -A "$UA" \
    "https://images.pexels.com/photos/$id/pexels-photo-$id.jpeg?auto=compress&cs=tinysrgb&w=1280&h=853&dpr=1" \
    -o "$out" || echo "  FAIL: $id"
}

echo "=== homepage-hero ==="
dl_unsplash "RoGw9buwZBg"   "homepage-hero" "woman-headphones-desk"
dl_pexels   "6779612"       "homepage-hero" "woman-airpods-laptop"
dl_pexels   "16924722"      "homepage-hero" "man-earbuds-from-behind"
dl_pexels   "5356702"       "homepage-hero" "woman-wireless-earbuds"

echo "=== hiring ==="
dl_unsplash "h0SVizhJyLw"   "hiring" "woman-desk-screen"
dl_unsplash "PIM07Y2OHzE"   "hiring" "woman-cardigan-macbook"
dl_unsplash "pg2eJwNVpvY"   "hiring" "woman-interviewing-notes"
dl_unsplash "8jwCWlsBys8"   "hiring" "woman-professional-1"
dl_unsplash "vLwH8bWoi_8"   "hiring" "woman-workspace-macbook"
dl_unsplash "Nnv0DHFG1Ds"   "hiring" "woman-coffee-shop-macbook"
dl_pexels   "5060815"       "hiring" "businessman-laptop-desk"
dl_pexels   "8428060"       "hiring" "businessman-laptop-documents"
dl_pexels   "7698800"       "hiring" "diverse-team-laptop"
dl_pexels   "9301868"       "hiring" "diverse-colleagues-office"

echo "=== customer-discovery ==="
dl_unsplash "hb_3LeP8G-w"   "customer-discovery" "woman-whiteboard-focused"
dl_unsplash "MgstZz0n6JE"   "customer-discovery" "man-whiteboard-concentration"
dl_unsplash "ajTN690FnUg"   "customer-discovery" "hand-whiteboard-diagram"
dl_unsplash "HUuWNQmW58A"   "customer-discovery" "sticky-notes-cluster"
dl_unsplash "3070czUj2ro"   "customer-discovery" "woman-sticky-notes-wall"
dl_unsplash "38HJarsEyMM"   "customer-discovery" "team-planning-board"
dl_unsplash "S3JdHNXSfnA"   "customer-discovery" "yellow-orange-sticky-notes"
dl_unsplash "Xe8mdKHpXTY"   "customer-discovery" "sticky-notes-glass-wall"
dl_unsplash "l_jwwoDi88I"   "customer-discovery" "people-planning-board"
dl_pexels   "1181343"       "customer-discovery" "man-whiteboard-planning"
dl_pexels   "4463588"       "customer-discovery" "entrepreneur-whiteboard"
dl_pexels   "6804078"       "customer-discovery" "man-sticky-notes-wall"
dl_pexels   "7680063"       "customer-discovery" "hand-pen-sticky-notes"
dl_pexels   "12797275"      "customer-discovery" "sticky-notes-organizing"
dl_pexels   "37027157"      "customer-discovery" "vibrant-sticky-notes-wall"
dl_pexels   "15543114"      "customer-discovery" "whiteboard-sticky-notes"
dl_pexels   "6592364"       "customer-discovery" "orange-sticky-note-glass"
dl_pexels   "7366"          "customer-discovery" "person-writing-board"
dl_pexels   "3854816"       "customer-discovery" "writing-pink-sticky-notes"

echo "=== user-research ==="
dl_unsplash "c3IwI6AmExM"   "user-research" "woman-sketching-laptop"
dl_unsplash "egzaAVwBYrY"   "user-research" "woman-glasses-notebook"
dl_pexels   "4240492"       "user-research" "woman-notes-laptop"
dl_pexels   "7034444"       "user-research" "woman-notes-diary"
dl_pexels   "3747137"       "user-research" "woman-writing-notebook"
dl_pexels   "5386490"       "user-research" "woman-writing-notebook-2"
dl_pexels   "6964479"       "user-research" "person-gold-pen-notebook"
dl_pexels   "3184654"       "user-research" "person-writing-notebook"

echo "=== legal-intake ==="
dl_unsplash "ze6TKkZeBTY"   "legal-intake" "female-lawyer-papers"
dl_unsplash "lXUatG8ukOg"   "legal-intake" "reviewing-settlement-docs"
dl_unsplash "qGTymDfxq6A"   "legal-intake" "paper-files-pen-desk"
dl_unsplash "MTqaqBY6lfA"   "legal-intake" "colored-binders-shelf"
dl_pexels   "7841442"       "legal-intake" "attorney-documents-desk"
dl_pexels   "7841463"       "legal-intake" "female-attorney-signing"
dl_pexels   "7841432"       "legal-intake" "lawyer-reading-documents"
dl_pexels   "7841445"       "legal-intake" "female-lawyer-holding-docs"
dl_pexels   "7680681"       "legal-intake" "desk-receipts-documents"
dl_pexels   "8353764"       "legal-intake" "documents-binder-desk"
dl_pexels   "8297536"       "legal-intake" "binders-office-table"
dl_pexels   "8297022"       "legal-intake" "folders-calculator-laptop"
dl_pexels   "17018372"      "legal-intake" "ring-binders-documents"
dl_pexels   "8872486"       "legal-intake" "man-woman-armchairs-interview"

echo "=== hr-people ==="
dl_unsplash "fV-HErZ7mt4"   "hr-people" "businessman-office-window"
dl_unsplash "hKMm6lw_HQM"   "hr-people" "woman-bay-window"
dl_pexels   "5717622"       "hr-people" "businesswoman-large-window"
dl_pexels   "7964149"       "hr-people" "asian-businesswoman-coffee"
dl_pexels   "5673495"       "hr-people" "woman-laptop-coffee-window"
dl_pexels   "8124401"       "hr-people" "bearded-man-glass-window"
dl_pexels   "5717270"       "hr-people" "businesswoman-office-window"

echo "=== audit-compliance ==="
dl_unsplash "1pqQDU3teIM"   "audit-compliance" "woman-documents-conference"
dl_unsplash "aj3qqRGzCkk"   "audit-compliance" "person-suit-folders"
dl_pexels   "8112129"       "audit-compliance" "male-reviewing-paperwork"
dl_pexels   "8297362"       "audit-compliance" "documents-mans-desk"

echo "=== dashboard-data ==="
dl_unsplash "JKUTrJ4vK00"   "dashboard-data" "laptop-analytics-charts"
dl_unsplash "hpjSkU2UYSU"   "dashboard-data" "laptop-statistics"
dl_unsplash "eveI7MOcSmw"   "dashboard-data" "macbook-analytics-dashboard"
dl_unsplash "nMqqEFhInkY"   "dashboard-data" "minimalist-workspace-laptop"
dl_pexels   "4405384"       "dashboard-data" "laptop-analytical-program"

echo "=== how-it-works-typing ==="
dl_unsplash "NCtxm2W3eKg"   "how-it-works-typing" "overhead-hands-typing-coffee"
dl_unsplash "gMw9UO_fDpw"   "how-it-works-typing" "overhead-typing-stationery"
dl_unsplash "uIu2_j7QAsU"   "how-it-works-typing" "closeup-typing-coffee"
dl_pexels   "7580642"       "how-it-works-typing" "overhead-hands-keyboard"
dl_pexels   "8123859"       "how-it-works-typing" "hands-wireless-keyboard"
dl_pexels   "5185145"       "how-it-works-typing" "topdown-hands-white-keyboard"
dl_pexels   "6894197"       "how-it-works-typing" "multiple-hands-laptop"

echo "=== how-it-works-debrief ==="
dl_unsplash "dKuAHsGbrQM"   "how-it-works-debrief" "woman-glasses-computer-intently"
dl_unsplash "gqzh0lSXo7g"   "how-it-works-debrief" "man-reading-contract-laptop"
dl_pexels   "7792857"       "how-it-works-debrief" "woman-hand-chin-laptop"
dl_pexels   "5717757"       "how-it-works-debrief" "man-desk-charts-laptop"
dl_pexels   "6779339"       "how-it-works-debrief" "professional-analyzing-data"

echo "=== about-team ==="
dl_unsplash "Eo5CDaYgVgo"   "about-team" "man-beard-window-light"
dl_unsplash "hpprnkQzggs"   "about-team" "man-outdoors-golden-hour"
dl_unsplash "Iz0t_S0shko"   "about-team" "woman-burgundy-indoor"
dl_pexels   "7888769"       "about-team" "man-sitting-large-window"
dl_pexels   "37389134"      "about-team" "woman-contemplative-outside"
dl_pexels   "6262545"       "about-team" "woman-modern-office"
dl_pexels   "30539629"      "about-team" "woman-thought-city-window"

echo "=== about-cafe ==="
dl_unsplash "GiIZSko7Guk"   "about-cafe" "woman-back-computer-cafe"
dl_unsplash "ulj8F90yd0k"   "about-cafe" "person-laptop-wooden-cafe"
dl_pexels   "26611985"      "about-cafe" "woman-table-cafe-back"
dl_pexels   "31499315"      "about-cafe" "silhouette-laptop-cafe"
dl_pexels   "34810130"      "about-cafe" "young-woman-laptop-outdoors"

echo "=== closing-cta ==="
dl_unsplash "f2CheATLMIU"   "closing-cta" "table-stools-brick-wall"
dl_unsplash "Wb4zPjTSZMo"   "closing-cta" "two-chairs-scandinavian"
dl_unsplash "P1vIMEmJDik"   "closing-cta" "armchairs-city-window"
dl_pexels   "5824550"       "closing-cta" "office-chair-window"
dl_pexels   "5824540"       "closing-cta" "armchair-table-window"

echo "=== help-center ==="
dl_unsplash "16XP6JpbcAk"   "help-center" "hands-backlit-keyboard-marble"
dl_pexels   "5185145"       "help-center" "topdown-hands-white-keyboard"
dl_pexels   "6894197"       "help-center" "multiple-hands-laptop-2"

echo "=== team-collaboration ==="
dl_unsplash "-uHVRvDr7pg"   "team-collaboration" "colleagues-coffee-shop-laptop"
dl_unsplash "hCb3lIB8L8E"   "team-collaboration" "small-team-working-table"
dl_pexels   "6150377"       "team-collaboration" "colleagues-looking-laptop"
dl_pexels   "5325107"       "team-collaboration" "three-people-laptop"

echo "=== time-back ==="
dl_unsplash "j9vyjfKPHgk"   "time-back" "man-relaxing-colorful-office"
dl_unsplash "irqy6S6IFak"   "time-back" "man-relaxed-home-desk"
dl_pexels   "5216276"       "time-back" "man-smiling-hammock"
dl_pexels   "12903094"      "time-back" "professional-woman-outdoor-cafe"

echo "=== misc (additional URLs) ==="
dl_unsplash "05HLFQu8bFw"   "misc" "unsplash-05HLFQu8bFw"
dl_unsplash "94f-Xr7M1rc"   "misc" "unsplash-94f-Xr7M1rc"
dl_unsplash "Ak-Q4g12E6A"   "misc" "unsplash-Ak-Q4g12E6A"
dl_unsplash "FJj9JnT-scY"   "misc" "unsplash-FJj9JnT-scY"
dl_unsplash "IXbUjYOjtf8"   "misc" "unsplash-IXbUjYOjtf8"
dl_unsplash "RP1LSD4noEw"   "misc" "unsplash-RP1LSD4noEw"
dl_unsplash "TFRkbW3hwbY"   "misc" "unsplash-TFRkbW3hwbY"
dl_unsplash "VttExh4PX3A"   "misc" "unsplash-VttExh4PX3A"
dl_unsplash "XN4T2PVUUgk"   "misc" "unsplash-XN4T2PVUUgk"
dl_unsplash "Ydx_gE9qpA8"   "misc" "unsplash-Ydx_gE9qpA8"
dl_unsplash "ZwzB7C8lPDI"   "misc" "unsplash-ZwzB7C8lPDI"
dl_unsplash "bhODg0B9iCs"   "misc" "unsplash-bhODg0B9iCs"
dl_unsplash "cT8EMwebBNU"   "misc" "unsplash-cT8EMwebBNU"
dl_unsplash "gr2KN6sW5wk"   "misc" "unsplash-gr2KN6sW5wk"
dl_unsplash "holRjVu30j8"   "misc" "unsplash-holRjVu30j8"
dl_unsplash "ikJyqzF-UrU"   "misc" "unsplash-ikJyqzF-UrU"
dl_unsplash "kMw7VdjCzC8"   "misc" "unsplash-kMw7VdjCzC8"
dl_unsplash "oKHwBexVing"   "misc" "unsplash-oKHwBexVing"
dl_unsplash "oTcaW8Pqv3U"   "misc" "unsplash-oTcaW8Pqv3U"
dl_unsplash "rBpTZ6msfgs"   "misc" "unsplash-rBpTZ6msfgs"
dl_unsplash "rcq3PwyweDQ"   "misc" "unsplash-rcq3PwyweDQ"
dl_unsplash "szAaw9Xo2lk"   "misc" "unsplash-szAaw9Xo2lk"
dl_unsplash "zlFM8uuNd6U"   "misc" "unsplash-zlFM8uuNd6U"
dl_pexels   "7749054"       "misc" "pexels-7749054"
dl_pexels   "8872157"       "misc" "pexels-blond-woman-whiteboard"
dl_pexels   "7653975"       "misc" "pexels-man-writing-whiteboard"

echo ""
echo "=== Done! ==="
echo "Checking counts by folder..."
for dir in /Users/wc-design/Downloads/Anyinterview.to/photography/*/; do
  count=$(find "$dir" -name "*.jpg" 2>/dev/null | wc -l | tr -d ' ')
  echo "  $(basename $dir): $count images"
done
